dist: xenial
language: python
python:
  - "3.7"
  - "2.7"
env:
  - MINIMUM_INSTALL=false
  - MINIMUM_INSTALL=true

before_install:
  - if [[ "$MINIMUM_INSTALL" = true ]]; then
      pip install -r min-requirements.txt;
    fi
install: pip install .
script:
  - pip install pytest~=3.6.1 pytest-cov~=2.4
  - pytest --cov=xena_gdc_etl
  - pip freeze

jobs:
  include:
    - stage: lint
      script: 
        - pip install flake8
        - flake8
  allow_failures:
    - stage: lint

notifications:
  email: false
