language: python
matrix:
  include:
    - name: "Python 3.7 minimum install"
      python: 3.7
      dist: xenial
      install:
        - pip install -r min-requirements.txt
        - pip install .
        - pip install pytest~=3.6.1 pytest-cov~=2.4
script: pytest --cov=xena_gdc_etl || pip freeze

jobs:
  include:
    - stage: deploy
      python: 3.7
      dist: xenial
      script: pip install flake8 || flake8

notifications:
  email: false
