sudo: required
language: python
python:
  - 3.6
  - 2.7
notifications:
  email: false
stages:
  - test
  - lint

.disable_global: &disable_global
  before_install: false
  install: true
  before_script: false
  after_success: false
  after_failure: false

.lint: &lint
  <<: *disable_global
  python: 3.6
  stage: lint
  script: make lint


jobs:
  include:
    - *lint
    - python: 3.6
      name: "python-3-min-req"
      <<: *disable_global
      install: make min-req-install
      script: make test
    - python: 2.7
      name: "python-2-min-req"
      <<: *disable_global
      install: make min-req-install
      script: make test
  allow_failures:
    - *lint

stage: test

install: make install
script:
  - make test
