sudo: required
language: python
python:
  - 3.6
  - 2.7
notifications:
  email: false
stages:
  - test
  - lint

.disable_global: &disable_global
  before_install: false
  install: true
  before_script: false
  after_success: false
  after_failure: false

.lint: &lint
  <<: *disable_global
  python: 3.6
  stage: lint
  install: pip install flake8
  script: flake8


jobs:
  include:
    - *lint
    - python: 3.6
      env: MINREQ=1
    - python: 2.7
      env: MINREQ=1
  allow_failures:
    - *lint

stage: test

script:
  - pytest --cov=xena_gdc_etl
  - pip install .
  - pip freeze

before_install:
  - if [[ -f min-requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min-requirements.txt requirements.txt;
    fi
  - pip install -r requirements.txt
  - pip install pytest~=3.6.1 pytest-cov~=2.4
